### ISSUE TITLE
question

### ISSUE THREAD

**Issue by prashantrbs** [sumitbera/WebAppAutomation#13]
Hi Sumit,

I'm so sorry for bothering you again.

I have followed the same setup that you have mentioned in the blog still i am unable to execute my UI tests in docker compose docker and under build environment i selected all options correctly 

when i trigger tests it just stuck here, please find ss
![image](https://user-images.githubusercontent.com/44323121/225266171-87f7cbd7-b15b-416f-9580-d086895c892f.png)

i have used your buildspec.yml and docker-compose.yml
Remote URL: http://localhost:4444/wd/hub

If let me know whats wrong i am doing.

Like we discuss last time regarding execution tests on ec2 instance docker. i tried this but i m not sure how to establish connection between my codepipeline and Ec2 instance. if you have any guide can you please share?

Thanks for your valuable time.

**Comment by sumitbera** [comment]
Hi Prashant, Is that the max number of log lines you can provide ? Wanted to check with you few things
1. I assume the selenium grid wasn't setup with the docker compose step, which means the compose up step is failing is that what you see in the logs ?
2. Secondly, what happens when you run the docker compose on your local machine? 

The problem I see could be the nodes of firefox and chrome are not getting registered to the grid and the compose is not coming up because of that. If that's the issue I'll push a fix to docker compose no worries :)

**Comment by prashantrbs** [comment]
Hello Sumit,

i checked locally. yes it's not registering chrome and firefox to grid.

i will send log Sumit.. its quite lengthy 

Thanks

**Comment by sumitbera** [comment]
Hi Prashant,
I've fixed the docker compose.yml, had to add few port configs, considering it wasn't updated in a while. Please refer my latest commit. I can see the grid is registering the node properly. Please let me know if the test works after the latest changes to docker compose.

Here is the screenshot on how it's looking on my local

![image](https://user-images.githubusercontent.com/12911549/225286839-12e1988d-0df8-405c-9fc7-44d1a74aeda8.png)

Here is how the local grid looks like after registering the node.

![image](https://user-images.githubusercontent.com/12911549/225287034-7b411fd8-63da-4920-bcca-9b26fb520099.png)

Feel free to raise any issues if it still doesn't work

**Comment by prashantrbs** [comment]
Thanks, Sumit, 

i will check it now and the remote URL still be localhost:4444? 

Thanks.

**Comment by prashantrbs** [comment]
Hi Sumit,

i am getting command issue previously it was working 

![image](https://user-images.githubusercontent.com/44323121/225289201-e8af2ad3-464b-406c-bd61-0fad25e7f825.png)

Thanks

**Comment by prashantrbs** [comment]
Sorry for the multiple replies. locally it working but in aws pipeline, i am getting the above issue.

Thanks.

**Comment by sumitbera** [comment]
Hi Prashant
Not sure if the docker daemon is running properly in the pipeline. Can you try adding these statements in the buildspec.yml Just try to add these statements and give it a try if it's working for you or not

In case you have selected **ubuntu machine** for your pipeline

sudo chmod 666 /var/run/docker.sock
sudo service docker start && docker-compose up -d

Else if the machine is Linux based then try
sudo groupadd docker
sudo usermod -aG docker $USER
sudo docker-compose up -d

**Comment by prashantrbs** [comment]
Hi Sumit,

Yes i have selected ubuntu machine. i tried these commands i got below error
![image](https://user-images.githubusercontent.com/44323121/225294026-f90f72e4-4df4-403d-9c1e-3936c11ad233.png)


then i just tried **sudo service docker start && docker-compose up -d**
![image](https://user-images.githubusercontent.com/44323121/225294205-c444d3c6-a76b-4c9d-8b86-3d892b0fb45d.png)

I will also search for a possible fixes for this issue.

Thanks

**Comment by prashantrbs** [comment]
I fixed this issue. i just checked below check box
![image](https://user-images.githubusercontent.com/44323121/225300268-250590f5-384e-425b-adcd-8bd75467786c.png)


However, its just stuck after the node added. Please find the logs
`selenium-hub| 11:32:30.381 INFO [GridModel.setAvailability] - Switching Node 31ef993c-d868-444f-a213-c251fbb3942d (uri: http://172.19.0.4:5555) from DOWN to UP

selenium-hub| 11:32:30.381 INFO [LocalDistributor.add] - Added node 31ef993c-d868-444f-a213-c251fbb3942d at http://172.19.0.4:5555. Health check every 120s

firefox_1 | 11:32:30.402 INFO [NodeServer.lambda$createHandlers$2] - Node has been added`

Thanks

**Comment by sumitbera** [comment]
Hi Prashant,

What's the command you are running, I saw in above screenshot you are running docker-compose up. If that's the case please pass **-d** along with the command, -d helps to run the containers in detached or background mode. The reason why you are stuck is because the containers are not running in detached mode. Let me know the finding.
The command should look like **"docker-compose up -d"**

Thanks

**Comment by prashantrbs** [comment]
Hi Sumit, 

Yes, its working after adding -d but I got another issue with your docker-compose.yml file. It worked well in the first run then i tried 2 time it says the following error.
![image](https://user-images.githubusercontent.com/44323121/225522374-84189147-6e12-47e5-bc3c-9f52e7689efc.png)

so i used my own docker-compose.yml file and it work well. i am not sure what was the issue with your docker compose file.

Here is mine:
`version: "3"

services:
  chrome:
    image: selenium/node-chrome:4.5.0-20221017
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444

  selenium-hub:
    image: selenium/hub:4.5.0-20221017
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
      - "4445:4445"`

Thanks Sumit.

**Comment by prashantrbs** [comment]
I would like to appreciate the blog content you posted . it's pretty straightforward and it helps a lot for beginners like me.

I m not DevOps guy so scratch my head to understand docker ci/cd and Thanks again Sumit.

**Comment by sumitbera** [comment]
Hi Prashant, 
I saw the issue you observed in the logs **"You have reached your pull rate limit..."** this usually comes when you reached to your limit of pulling the docker image from the docker hub (rate limit issue). So if you try after sometime It will work again. What you can do for better experience is that You create an account on Docker Hub and use the credentials from that account to access Docker in your CodeBuild builds. Docker provides a free plan that provides a much higher limit for accessing images.

Let me know if there are any more issues, if not feel free to close the question and you can raise any other issue in future.

Best Regards,
Sumit

**Comment by sumitbera** [comment]
I'm glad the article helped, feel free to reach out for any issues and I'll happy to help you out

**Comment by prashantrbs** [comment]
> 

Sure i will create and and do this. Thanks again i am closing this ticket.

**Comment by prashantrbs** [comment]
> Hi Prashant, I saw the issue you observed in the logs **"You have reached your pull rate limit..."** this usually comes when you reached to your limit of pulling the docker image from the docker hub (rate limit issue). So if you try after sometime It will work again. What you can do for better experience is that You create an account on Docker Hub and use the credentials from that account to access Docker in your CodeBuild builds. Docker provides a free plan that provides a much higher limit for accessing images.
> 
> Let me know if there are any more issues, if not feel free to close the question and you can raise any other issue in future.
> 
> Best Regards, Sumit

Sure i will create an account and do this. Thanks again i am closing ticket
